production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database:
        <%= ENV['DB_NAME'] || 'funny_movies_development' %>
      hosts:
        - localhost
        # - localhost:27017
        # - <%= ENV['DB_HOST'] %>
      options:

  # Configure Mongoid specific options. (optional)
  options:

test:
  clients:
    default:
      database: funny_movies_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
